version: "3.8"

services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8084:8084"
    networks:
      - task_management_network
networks:
  task_management_network:
    external: true

